### ISSUE TITLE
Select Icon

### ISSUE THREAD

**Issue by carosouza** [bestproject/mod_bpicon#4]
Hello, how to use a different icon, which when you click select nothing happens (no modal window appears). I am testing on a Joomla 3.6.0, PHP 6.5.18.

Thank you

Carlos

**Comment by artur-stepien** [comment]
I need to know the module version. Also please provide the browser console output (from module options view). It looks like JS problem.

**Comment by carosouza** [comment]
Hello Arthur, thanks for answering. I was testing the module in localhot and why not open the modal with icon options, but installed the online site and it works perfectly. Congratulations on the excellent module !!

Success to you!

Att: module version is 1.5.2 (gitub download)

Carlos

**Comment by carosouza** [comment]
Hello, follow translate for pt-BR

Thanks!
[pt-BR.zip](https://github.com/bestproject/mod_bpicon/files/303052/pt-BR.zip)
